// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("ImageProcessing")>]
[<assembly: AssemblyProductAttribute("ImageProcessing")>]
[<assembly: AssemblyVersionAttribute("0.1.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2023-07-02T00:00:00.0000000+01:00")>]
[<assembly: AssemblyFileVersionAttribute("0.1.0")>]
[<assembly: AssemblyInformationalVersionAttribute("0.1.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","be0401d366e1c3b8c869a015b191081b6ee16543")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "ImageProcessing"
    let [<Literal>] AssemblyProduct = "ImageProcessing"
    let [<Literal>] AssemblyVersion = "0.1.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2023-07-02T00:00:00.0000000+01:00"
    let [<Literal>] AssemblyFileVersion = "0.1.0"
    let [<Literal>] AssemblyInformationalVersion = "0.1.0"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "be0401d366e1c3b8c869a015b191081b6ee16543"
